version: "3"

services:
    step-ca:
        image: smallstep/step-ca
        restart: unless-stopped
        ports:
            - "443:443"
        volumes:
            - step_data:/home/step
volumes:
  step_data:
    external: true