version: "3"

services:
    adguard:
        image: adguard/adguardhome
        restart: unless-stopped
        ports:
            - "53:53/tcp"     # plain DNS
            - "53:53/udp"     # plain DNS
            #- "67:67/udp"     # DHCP
            #- "68:68/udp"     # DHCP
            #- "68:68/tcp"     # DHCP
            - "80:80/tcp"     # admin panel
            - "443:443/tcp"   # admin panel, if HTTPS is configured, DNS over HTTPS
            - "443:443/udp"   # admin panel, if HTTPS is configured, DNS over HTTPS
            - "3000:3000/tcp" # admin panel
            - "853:853/tcp"   # DNS over TLS
            - "784:784/udp"   # DNS over Quic
            - "853:853/udp"   # DNS over Quic
            - "8853:8853/udp" # DNS over Quic
            - "5443:5443/tcp" # DNSCrypt
            - "5443:5443/udp" # DNSCrypt
        volumes:
            - "/my/own/workdir:/opt/adguardhome/work"
            - "/my/own/confdir:/opt/adguardhome/conf"
